### ISSUE TITLE
Allow to define a whitelist of url parameters.

### ISSUE THREAD

**Issue by discordier** [hofff/contao-shariff#1]
For the sake of canonical urls and reader pages, one should be allowed to have a whitelist of URL parameters that are accepted.

Imagine:
1. Reader page with URL parameter "item" and value "fooBar"
2. A sortable list on the same page providing related items.
3. Clicking sorting columns of the list will now produce: `.../item/fooBar?sort=title`.

By defining a whitelist containing only "item", the irrelevant parameter "sort" will get stripped and should be used as canonical url.

**Comment by backbone87** [comment]
wo sollte das konfiguriert werden? pro element? global?

**Comment by frontendschlampe** [comment]
That's a good question. I think it would be enough if we provide it as global setting, because the parameters should be the same on the whole website. Maybe there will be an option to ignore the whitelist in modules or CE?!

**Comment by backbone87** [comment]
@discordier @frontendschlampe können wir hier mal irgendwie feedback bekommen wie sehr gewünscht dieses feature ist?

**Comment by frontendschlampe** [comment]
Ich fände das als Feature schon sehr interessant - wir sollten uns hier mal zeitnah mit @discordier austauschen

**Comment by frontendschlampe** [comment]
Grundsätzlich wäre das Feature schon interessant, aber aktuell sehen wir hierfür keinen Bedarf. Wenn es für ein spezielles Projekt benötigt wird, könnte man schauen, wie man es einarbeitet.
