### ISSUE TITLE
iPhone URL im Text

### ISSUE THREAD

**Issue by cgpro** [hofff/contao-shariff#11]
Wenn eine mailto URL wie per iPhone aufgerufen wird, ist die URL nicht mehr im Mailtext vorhanden da sie in spitzen klammern steht.

Beispiel (geht nicht):
http://www.domain.tld 

Besser wärs per Default die <> weg zu lassen. Wenn man es per Insert-Tag ##url## eingibt, gehts wunderbar.

**Comment by backbone87** [comment]
das ist die standard einstellung vom shariff.js https://github.com/heiseonline/shariff/blob/master/src/js/shariff.js#L89

**Comment by cgpro** [comment]
ok, vielleicht hilft das ticket dem ein oder anderen wenn das passiert.
