### ISSUE TITLE
Kann Formular mit Sicherheitsabfrage nicht mehr absenden, wenn Shariff auf der Seite eingebunden ist

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-shariff#12]
Formular wird ausgefüllt und abgesendet > Seite läd neu > Man soll noch mal die Sicherheitsabfrage ausfüllen...

Im Log steht leider nichts.

Viele Grüße

**Comment by frontendschlampe** [comment]
wie schon im Mumble besprochen, sollte das in der aktuellsten Version behoben sein! ;-)
