### ISSUE TITLE
Clear cached share counts, whenever share button is used

### ISSUE THREAD

**Issue by felixww** [hofff/contao-shariff#13]
Issue: 
Share count is not updated when a share button is used (it is updated only after the respective cache has expired).

Proposed solution:
When a page is being shared, the matching share count cache should expire. 
Workaround: Clear all Shariff caches in  TL_HOME/system/tmp/ whenever a user clicks one of the share buttons.

**Comment by backbone87** [comment]
On low traffic pages this wouldnt be a problem at all, but on higher traffic pages with lots of shares, you permanently would invalidate the cache rendering it to be useless?

Is reducing the cache duration a band-aid fix to this? What would be an acceptable TTL of the cache? 60s?

**Comment by felixww** [comment]
60s would work, sure!

I looked at heiseShariff/Backend.php and it looks promising to add a method that 
would call ZendCache::removeItem(). Would it be possible to call the shariff backend "on click"
and remove the particular counter from the cache?

**Comment by backbone87** [comment]
the TTL is configurable per root page since v3
