### ISSUE TITLE
[Enhancement] Shariff Button mit Like-Funktion

### ISSUE THREAD

**Issue by akroii** [hofff/contao-shariff#14]
Anscheinend enhält der Fork von [@P1tt187/shariff](https://github.com/P1tt187/shariff) eine Like-Funktion:
https://github.com/P1tt187/shariff/blob/e56d5d4cb6f1494b497e335c7f59887283d7423e/src/js/services/facebook-like.js#L1-L18

https://www.datenschutz-notizen.de/social-media-button-sharrif-kann-doch-liken-2310022/

Kannst du dieses in dein Projekt einbauen?

**Comment by frontendschlampe** [comment]
Hallo @akroii, vielen Dank für Deinen Hinweis. Wir haben uns das mal angeschaut, aber nach Rücksprache mit @backbone87 werden wir das nicht einarbeiten. Die Basis für den verlinkten Fork ist eine relativ alte Version von Shariff. Wir müssten es also erstmal aktualisieren. Des weiteren sehen wir auch ein Stück weit die Gefahr, dass es die Grundlage von Shariff, nämlich die "sichere" Art Inhalte zu teilen in Gefahr bringt. Shariff ist und bleibt ein Tool zum Sharen und nicht zum Liken. Wenn das so von Heise vorgesehen oder gewollt wäre, hätte man es sicherlich schon seitens Heise eingearbeitet. Vielen Dank für Dein Verständnis.

**Comment by backbone87** [comment]
Evtl mal mit einem Feature request bei Shariff direkt versuchen. Wenn es in die offizielle Lib eingelaut wurde, werden wir es hier übernehmen
