### ISSUE TITLE
Domain runs on PHP 5.6.30 CGI/FPM at All-Inkl, but contao-shariff 2.0.1 complains about 5.5.38 in package management

### ISSUE THREAD

**Issue by jscholtysik** [hofff/contao-shariff#16]
A domain of a client runs on PHP 5.6 CGI/FPM at All-Inkl. When I try to update the installed packages, the composer console window shows the following error message:

> $ /usr/bin/env php -d memory_limit=10G -d max_execution_time=900 composer.phar update --no-ansi --no-interaction --dry-run --prefer-dist
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hofff/contao-shariff 2.0.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - hofff/contao-shariff 2.0.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
    - Installation request for hofff/contao-shariff >=2.0.1.0,<2.1-dev -> satisfiable by hofff/contao-shariff[2.0.1].

The server which contains the domain runs on 5.5.38 Apache module, but the domain is set to 5.6.30 CGI/FPM at All-Inkl.
I checked all PHP settings with the support at All-Inkl, so asking the server for the Apache module instead of of the CGI module this must be the reason for the error message.

This is the Apache Version:
![bildschirmfoto 2017-07-24 um 23 46 38](https://user-images.githubusercontent.com/1425566/28546258-61efb516-70ca-11e7-9208-1fe98d6e7ae7.png)

An this is set for the domain:
![bildschirmfoto 2017-07-24 um 23 47 52](https://user-images.githubusercontent.com/1425566/28546326-93fb2e1e-70ca-11e7-83e2-52e52a9d96d1.png)

Because of the error message I'm not able to update the packages...

**Comment by MDevster** [comment]
Please use "php56" in the console to set the required php version

php56 -d memory_limit=10G -d max_execution_time=900 composer.phar update --no-ansi --no-interaction --dry-run --prefer-dist

**Comment by jscholtysik** [comment]
Thanks for the hint. Is it always the case that composer uses the Apache module instead of the defined CGI module?

**Comment by MDevster** [comment]
This depends on the server config and is different for each provider.

**Comment by backbone87** [comment]
> Is it always the case that composer uses the Apache module instead of the defined CGI module?

PHP Command Line has nothing to do with Apache or CGI. Its the other way around. CGI/FPM and Apache mod_php use the installed PHP (which contains a CLI and a Service executable). You have at least 2 PHP Versionen installed. Which version mod_php uses depends on the apache config. Which version CGI/FPM uses depends on the FPM config. Which version your shell uses depends on the shell config (PATH, aliase etc).
