### ISSUE TITLE
Facebook-ID Feld um counts anzeigen zulassen. 

### ISSUE THREAD

**Issue by srhinow** [hofff/contao-shariff#17]
Hallo,
mein Kunde hätte gern das die Likes im Facebook-Button angezeigt werden. Dazu gibt es aber kein Eingabefeld. Bitte ein solches Eingabefeld anlegen oder öffentlich angeben wo solch eine Variable gesetzt werden muss und wie diese dann heißen soll.

**Comment by frontendschlampe** [comment]
@backbone87 und ich haben uns das nochmal angeschaut und uns dazu Gedanken gemacht und wir haben uns dazu entschieden, dass wir die Eingabe der Facebook-ID nicht in Shariff direkt eingeben lassen wollen, da folgendes Problem besteht:

Es kann andere Erweiterungen oder manuelle FB-Scripte geben, die ebenfalls die FB-ID benötigen. Wenn also außerhalb von Shariff schon eine ID vorhanden ist, dann würde die ID mehrfach vorhanden sein und das wäre sehr ungünstig.

Man bräuchte deshalb eigentlich eine Erweiterung, die global ID's für diverse Dienste zur Verfügung stellt mit einer seitenbaumabhängigen Pflege.

Alternativ kann man die Facebook ID über *Zusätzliche <head>-Tags* im Seitenlayout einarbeiten.

@backbone87 Wie sieht der Code für die Einbindung eigentlich aus? Habe da jetzt auf die Schnelle nichts gefunden!? Gibt es dafür eigentlich einen allgemeinen Einbindecode?

**Comment by backbone87** [comment]
@frontendschlampe ich glaube du verwechselst was. Das was du meinst ist fb:app_id in den seiten (siehe https://developers.facebook.com/docs/sharing/webmasters#markup )

@srhinow möchte aber über das shariff backend (vom server aus) die like counts holen und dazu muss man auch die fb id angeben (ähnlich wie ein API key)

**Comment by frontendschlampe** [comment]
@backbone87 and me misunderstood us when we talked about the problem! ;-)

**Comment by backbone87** [comment]
facebook app credentials are configurable per root page since v3
