### ISSUE TITLE
IE8 has massive Problems with this JS

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-shariff#19]
Would be nice to wrap the js in conditional comments. Then the IE8 would ignore the js complete.

regards

**Comment by backbone87** [comment]
I really dont like to pull in such legacy stuff. I mean come on, its fkin IE8.

Anyway, you can override the template in your installation with the template from your PR (thats why I put script includes inside templates and not into the PHP classes).

@frontendschlampe Any comments?

**Comment by frontendschlampe** [comment]
I talked already to @MacKP and I tell him to make a PR. I also don't like it, but I would add it to v2, because we want to make a new v3 and there we don't add it.

**Comment by MacKP** [comment]
Yeah, it's IE8 :( 
But without that conditional comments the IE8 breaks complete.. with that the IE8 just ignores it ;-)

regards

**Comment by backbone87** [comment]
As discussed in mumble, no IE8 support. You can customize the template by overriding it in the installations
