### ISSUE TITLE
Problem with Contao 4 paths

### ISSUE THREAD

**Issue by ufeldmann** [hofff/contao-shariff#21]
I have still a problem with the Contao 4 paths.
https://github.com/hofff/contao-shariff/pull/18

Could you verify this? Thx. ;)

**Comment by Toflar** [comment]
ping @backbone87 ;)

**Comment by backbone87** [comment]
https://github.com/hofff/contao-shariff/pull/18#discussion_r157969778

why are there 2 different paths in c4? Or is the one merged the wrong one?

**Comment by ufeldmann** [comment]
I think the merged one is wrong.

/vendor/hoff/contao-shariff/contao-module/endpoints/counts.php

So you need to go 5 folders above and not 6.

**Comment by backbone87** [comment]
@Toflar can you confirm? did you test your PR?

**Comment by Toflar** [comment]
I did not, asked @frontendschlampe to do so with you :)

**Comment by backbone87** [comment]
@ufeldmann if you remove one dir lvl, does it work for you?

**Comment by backbone87** [comment]
hopefully fixed in 2.0.3 @ufeldmann pls verify

**Comment by ufeldmann** [comment]
Works, thx

**Comment by backbone87** [comment]
contao 4 bundle is also available now since v3
