### ISSUE TITLE
sensio/framework-extra-bundle wurde als Abhängigkeit in Contao 4.4.24 entfernt

### ISSUE THREAD

**Issue by Ainschy** [hofff/contao-shariff#24]
Hi,
in Contao 4.4.24 wurde die Abhängigkeit zu sensio/framework-extra-bundle entfernt.

` [Semantical Error] The annotation "@Sensio\Bundle\FrameworkExtraBundle\Conf
  iguration\Route" in class Hofff\Contao\Shariff\Action\ShareCountsAction doe
  s not exist, or could not be auto-loaded in /www/htdocs/wXXXXXXX/webseiten/
  zzzzzzzzz/vendor/hofff/contao-shariff/src/Action/ (which is being imported
  from "/www/htdocs/wXXXXXXX/webseiten/zzzzzzzzz/vendor/hofff/contao-shariff/
  src/ContaoManager/../Resources/config/routing.xml"). Make sure annotations
  are installed and enabled.`

Edit:
Hab sie nun in meiner composer.json als Abhängigkeit eingetragen
`"sensio/framework-extra-bundle": "^3.0.2",`

**Comment by backbone87** [comment]
Danke für die info

**Comment by frontendschlampe** [comment]
@backbone87 kannst du das bitte mal prüfen und fixen?

**Comment by backbone87** [comment]
während der fehler hier klar auf meiner seite ist (man sollte sich nie auf transitive abhängigkeiten verlassen) verwundert mich das entfernen der abhängigkeit innerhalb einer bugfix version doch sehr. selbst in einer minor version wäre mir das noch zu wackelig. gibt es eine erklärung warum das auf einmal entfernt wurde?

**Comment by Ainschy** [comment]
Das eine Abhängigkeit in einem Bugfix entfernt wird fand ich auch doof und hab das Leo und Andy gegenüber erwähnt, ihrer Aussage dazu ist, wer eine Klasse benötigt sollte sicherstellen das sie installiert wird.

Ich kann Beides verstehen, jedoch ist das wenig hilfreich wenn ein Nutzer ohne Kenntnis der Abhängigkeiten in die Situation kommt die ganze Webseite nicht mehr aufrufbar ist.

**Comment by backbone87** [comment]
`sensio/framework-extra-bundle` wird ab 3.0.1 nicht mehr benötigt

**Comment by discordier** [comment]
Dafuer nun aber `"symfony/routing": "^3.3 |  ^4.0"`, welches du wieder nicht notiert hast und somit wieder ueber "jemand anderem" kommen muss.

Sollte nun irgendwann dieses package auch entfernt/abgeloest werden, dann hast du wieder dasselbe Problem.

In deiner `composer.json` solltest du alle Pakete die du zwingend erforderst (also route, dependency-injection, config, ...) eintragen. Ebenfalls sollten darin die verwendeten php extensions nach bedarf hinterlegt sein (`ext-json` z.B. sofern du `json_decode` verwendest).

**Comment by backbone87** [comment]
Die frage ist wie weit man da geht. In einem durchschnittlichen Contao-Bundle werden ja auch `symfony/dependency-injection`, `symfony/http-kernel` und `symfony/http-foundation` verwendet. Noch interessanter wirds wie man die container config behandelt. Wenn man auf services aus `symfony/framework-bundle` zurückgreift, ist das dann eine abhängigkeit? Da Contao selbst dieses package nutzt und somit dessen container config selbst exponiert gehört es dann zur BC promise?

Edit: Außerdem stellt das requiren vom `symfony/framework-bundle` nicht sicher, dass dessen container config auch tatsächlich geladen wird.

**Comment by discordier** [comment]
1. Alle Pakete mit Klassen, welche in deinem Code verwendet werden (via `use` oder mit fqcn) muessen in der `composer.json` required werden, da ansonsten jemand anders ggf. einen neuen Major required oder aber eine seiner dependencies entfernt und du dann im Regen stehst (was eben hier passiert ist).
1.1. Ausnahme sind hierbei soft-dependencies welche Zusatzfunktionalitaet liefern, diese sollten in die `suggests` wandern.
2. Dependencies gehoeren NIE zur bc promise, da sie nicht die ABI des eigenen Pakets betreffen, Ausnahme hiervon sind lediglich Klassen, welche als Parameter hin und her gereicht werden und die somit wieder unter 1. fallen.
