### ISSUE TITLE
Compatible with >4.4?

### ISSUE THREAD

**Issue by JohnGiddi** [hofff/contao-shariff#25]
Hello !
Is this extension compatible with  >4.4?

Thank you!

Greetings
JohnGiddi

**Comment by backbone87** [comment]
Yes it is. You can also check the compatibility easily yourself by having a look into the require section of the composer.json file of the extension in question. If it contains a requirement for contao/core-bundle with ^4.4 the developer/s of the extension declared it as compatible

**Comment by JohnGiddi** [comment]
Thank you! That sounds good!
Greetings
John Giddi
