### ISSUE TITLE
Missing Button type (german "Button-Stil")

### ISSUE THREAD

**Issue by cmichael-de** [hofff/contao-shariff#26]
In an older version there is a button type ... is this feature removed now? https://nimb.ws/eahzBK

**Comment by frontendschlampe** [comment]
I don't know. I check with Contao 4.6.14 and Shariff 3.0.1 and I have the "Button-Stil" option.

<img width="1177" alt="bildschirmfoto 2019-02-21 um 22 51 15" src="https://user-images.githubusercontent.com/1232819/53204169-3f990f80-362b-11e9-9cc5-9fe20d3dc594.png">

**Comment by cmichael-de** [comment]
I am using Contao 4.4.32

**Comment by frontendschlampe** [comment]
and which version of contao-shariff?

**Comment by cmichael-de** [comment]
php -d memory_limit=-1 ../composer.phar require hofff/contao-shariff
Using version ^2.0 for hofff/contao-shariff
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing zendframework/zend-stdlib (3.2.1): Downloading (100%)         
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)         
  - Installing zendframework/zend-servicemanager (3.4.0): Downloading (100%)         
  - Installing zendframework/zend-eventmanager (3.2.1): Downloading (100%)         
  - Installing zendframework/zend-cache (2.8.2): Downloading (100%)         
  - Installing heise/shariff (6.0.1): Downloading (100%)         
  - Installing hofff/contao-shariff (2.0.4): Downloading (100%)

**Comment by frontendschlampe** [comment]
please use hoff/contao-shariff ^3.0

**Comment by cmichael-de** [comment]
Installed Version 3.0.1 with Contao-Manager ... I was not able to install/update the 3.0 with composer cli. Now the field occurs - everything is fine - thx a lot for your help!

**Comment by frontendschlampe** [comment]
With the current version 3.x you have to use Font Awesome v5 (see readme for v3), because the dependent packages of shariff don't support Font Awesome v4 anymore. If you want to use Font Awesome v4 you have to make your own stylings.

**Comment by cmichael-de** [comment]
Yes :-) I am a little bit lucky cause my theme is independent of fontawesome  - so it is easy to switch to v5. Thx for the Info.
