### ISSUE TITLE
Add Custom Orientation

### ISSUE THREAD

**Issue by cmichael-de** [hofff/contao-shariff#27]
Currently there is horizontally and vertically available, so you have to use one of these. To avoid conflicts with other project styles, it would be helpful to have a third Orientation for example "Keine" or "Individuell".

Currently I go to the template and comment out the: 
`/* $GLOBALS['TL_CSS']['shariff.css'] = 'bundles/hofffcontaoshariff/css/shariff.min.css'; */`

But then I loose the color and some shariff styles that I like to keep actually. So just a "clean" orientation would be great and does the job .

**Comment by frontendschlampe** [comment]
We're sorry, but this option is not supported by Shariff itself, that's why we won't support it. You could do as you said or overwrite the CSS by yourself.
