### ISSUE TITLE
Modul Titel

### ISSUE THREAD

**Issue by operatorone** [hofff/contao-shariff#28]
Is it possible to add a title in the module?

![shariff-module](https://user-images.githubusercontent.com/4036452/54019299-26e03c00-418b-11e9-9770-f9d7c8cd984b.jpg)

![shariff](https://user-images.githubusercontent.com/4036452/54019230-f9938e00-418a-11e9-930e-92c29e26b2ad.jpg)

**Comment by Stefko** [comment]
I have the same problem, see https://community.contao.org/de/showthread.php?72301-Shariff-3-0-1-unter-Contao-4-4-kein-Titel-m%C3%B6glich

**Comment by frontendschlampe** [comment]
Ww will try to fix asap.

**Comment by contaoacademy** [comment]
Hey @frontendschlampe, der Fehler ist im Moment noch existent.
Als Workaround kann man wie folgt vorgehen:
1. Neues Modul vom Typ HTML-Element anlegen und einen Titel vergeben.
2. Speichern
3. Modul umstellen auf Shariff
-> Der Titel bleibt dabei erst mal in der Datenbank gespeichert.

**Comment by frontendschlampe** [comment]
Verdammt ... die Zeit fehlt ... ich geb mein bestes, dass wir die Extension endlich aktualisieren können. :-/
