### ISSUE TITLE
Package is abandoned

### ISSUE THREAD

**Issue by dp-designpilot** [hofff/contao-shariff#29]
Hallo Nicky

**_Folgende Meldung erhalte ich wenn ich die Erweiterung zum Test markiere_**
Package operations: 6 installs, 0 updates, 0 removals
  - Installing zendframework/zend-stdlib (3.2.1)
  - Installing container-interop/container-interop (1.2.0)
  - Installing zendframework/zend-servicemanager (3.4.0)
  - Installing zendframework/zend-cache (2.9.0)
  - Installing heise/shariff (7.1.4)
  - Installing hofff/contao-shariff (3.0.3)
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.
Package zendframework/zend-cache is abandoned, you should avoid using it. Use laminas/laminas-cache instead.

Contao Version: 4.9.3

**Comment by frontendschlampe** [comment]
"abandoned" heißt verwaist. Jeder Entwickler kann zu jedem Zeitpunkt sein Paket als verwaist markieren – einfach so. Das bedeutet jedoch nicht, dass das Paket nicht mehr funktionstüchtig ist.

Es ist natürlich sinnvoll, hier die Abhängigkeiten zu aktualisieren und somit die entsprechenden Meldungen zu beheben. Dies wird in einem nächsten Update passieren.
