### ISSUE TITLE
only pass "Twitter via" to template if twitter sharing is active

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-shariff#3]

**Comment by backbone87** [comment]
warum?

**Comment by frontendschlampe** [comment]
... weil es ja nur bei Twitter genutzt wird?!

**Comment by backbone87** [comment]
wont fix, warum sollte twitter via ausgefüllt werden wenn man kein twitter share haben möchste, und selbst wenn schadet es nicht und es ist nur in der HTML source zu finden
