### ISSUE TITLE
Kompatibilität mit PHP 8 herstellen

### ISSUE THREAD

**Issue by contaoacademy** [hofff/contao-shariff#34]
Ich wollte heute eine Installation auf Contao 4.13 und PHP 8.1 umstellen. Beim "Pakete aktualisieren" bekomme ich allerdings einen Fehler:
```
hofff/contao-shariff[3.0.0, ..., 3.0.3] require php ^7.1 -> your php version (8.1.4.0) does not satisfy that requirement.
```

Vielen Dank im Voraus.

**Comment by frontendschlampe** [comment]
Hey @contaoacademy wir werden die Erweiterung Ende April im Rahmen eines Projektes aktualisieren … PHP 8 und auch Contao 4.13

**Comment by dmolineus** [comment]
Wir haben uns das ganze nochmal angeschaut. Leider scheint Heise die Weiterentwicklung für shariff eingestellt zu haben. Seit 2 Jahren gibt es hier keine Aktualisierung mehr, geschweige denn Support für PHP 8. Uns sind daher aktuell die Hände gebunden.

**Comment by contaoacademy** [comment]
@dmolineus Danke für die Rückmeldung. Wie geht Ihr jetzt bei euren Installationen vor? Auf PHP 7.4 bleiben oder entwickelt Ihr eine alternative Lösung?

**Comment by frontendschlampe** [comment]
@contaoacademy Dort, wo wir demnächst was machen müssen, werden wir Shariff entfernen, da es aus unserer Sicht einfach nicht mehr nötig ist. Jedes Betriebssystem bietet mittlerweile direkte Möglichkeiten, eine Seite direkt zu teilen. Da braucht es keine gesonderte Lösung direkt auf der Website. Wir werden es im Auge behalten. Falls sich seitens Heise doch noch etwas ergeben sollte, werden wir die Erweiterung auf jeden Fall aktualisieren. Eine Nachfrage, ob das Repo noch aktiv ist, wurde leider noch nicht beantwortet: https://github.com/heiseonline/shariff/issues/404 (lustig, dass es gerade das Issue 404 ist :-D)

**Comment by frontendschlampe** [comment]
@contaoacademy Was man auch noch beachten sollte: Shariff wurde ja ursprünglich dazu entwickelt, um die Likes einer Seite anzuzeigen. Diese Likes wurden bei Shariff nicht über den Client geholt, sondern über den Server, so dass keinerlei persönlichen Infos weitergegeben werden konnten. Dies wird ja praktisch nirgends mehr wirklich eingesetzt. Wenn es um das "einfache" Teilen einer Seite geht, dann können auch die Standard-Teilen-Buttons von Contao verwendet werden. Dies ist nur ein Link. Aber wie im vorherigen Kommentar schon erwähnt: die Teilen-Funktionalität ist seitens des Betriebssystems viel komfortabler und umfangreicher, als die eingeschränkte Funktionalität von entsprechenden Buttons auf einer Website direkt.

**Comment by contaoacademy** [comment]
Ich denke, ich werde zu folgender Erweiterung wechseln.
https://github.com/fritzmg/contao-sharebuttons

**Comment by bytehead** [comment]
Just for the record: https://github.com/heiseonline/shariff-backend-php/releases/tag/v10.0.0 - da gabs doch mal noch eine neue Version (v10.0.0) 😅

**Comment by frontendschlampe** [comment]
seriously?! … thank you for your information, but I don't think, that we will update the extension. Because of long time nothing happens, we replace/delete the extension in our installations.
