### ISSUE TITLE
Ordner im Zip

### ISSUE THREAD

**Issue by zonky2** [hofff/contao-shariff#6]
Hallo,

wäre es möglich die Ordnerstruktur so anzulegen, das man mit dem "Zip-Paket" ein Upload machen kann? z.Z. ist der eigentliche Ordner "/contao-module" - müsste aber sein "/hofff_shariff"

das bekommt man erst durch "Studium" der autoload raus...

**Comment by frontendschlampe** [comment]
Wie wir bereits im Mumble besprochen haben, ist die manuelle Installation auf Grund der externen Abhängigkeiten gar nicht so einfach. Ich habe aber bereits mit xtra gesprochen, dass wir im Juni/Juli einen Nightly-Build-Service auf unserer Website einrichten werden. Ich bitte noch im etwas Geduld ... :-)

**Comment by zonky2** [comment]
jut
