### ISSUE TITLE
Installations Anleitung für Contao

### ISSUE THREAD

**Issue by Vamiris** [hofff/contao-shariff#7]
Hallo,

gibt es eine Anleitung für das Modul für die manuelle Installation in Contao?

Das Modul + Sql wird gefunden und lässt ausführen. Jedoch scheitert das Modul daran, dass die Klasse "Module class "Hofff\Contao\Shariff\ModuleShariff" (module "hofff_shariff") does not exist" nicht existiert.

Im Autoload habe ich die Klassen aus dem ordner src hinzugefügt, bringt jedoch keine Änderung an dem Fehler.

Gruß
Christian

**Comment by frontendschlampe** [comment]
Wir binden https://github.com/heiseonline/shariff als externe Library via Composer ein, deshalb ist die manuelle Installation etwas "schwierig". Wie bereits in https://github.com/hofff/contao-shariff/issues/6 erwähnt, wollen wir das aber ändern und einen Nightly-Build-Service auf unserer Website einrichten. Wir brauchen dafür aber noch etwas Zeit! Wir geben Bescheid, sobald es soweit ist.
