### ISSUE TITLE
XING und LinkedIn

### ISSUE THREAD

**Issue by ghost** [hofff/contao-shariff#8]
Hallo zusammen,

wird contao-shariff noch um XING und LinkedIn erweitert?

Viele Grüße

**Comment by frontendschlampe** [comment]
Xing und LinkedIn haben wir soeben in der Version 1.1.0-beta hinzugefügt - könntest du es mal testen?

**Comment by ghost** [comment]
Auf elfa aktiviert. Keine Fehler gefunden. THX!!
